apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  
  name: ops.k8s.nearform.net
spec:
  additionalPolicies:
    node: |
      [
        {
          "Effect": "Allow",
          "Action": [
            "acm:ListCertificates",
            "acm:GetCertificate",
            "acm:DescribeCertificate",
            "autoscaling:DescribeAutoScalingGroups",
            "autoscaling:AttachLoadBalancers",
            "autoscaling:DetachLoadBalancers",
            "autoscaling:AttachLoadBalancerTargetGroups",
            "autoscaling:DetachLoadBalancerTargetGroups",
            "autoscaling:DescribeLoadBalancerTargetGroups",
            "cloudformation:*",
            "cloudwatch:ListMetrics",
            "cloudwatch:GetMetricStatistics",
            "cloudwatch:Describe*",
            "elasticloadbalancing:*",
            "elasticloadbalancingv2:*",
            "ec2:DescribeAccountAttributes",
            "ec2:DescribeInternetGateways",
            "ec2:DescribeInstances",
            "ec2:DescribeSubnets",
            "ec2:DescribeSecurityGroups",
            "ec2:DescribeRouteTables",
            "ec2:DescribeVpcs",
            "health:DescribeEvents",
            "iam:GetServerCertificate",
            "iam:CreateServiceLinkedRole",
            "iam:ListServerCertificates"
          ],
          "Resource": ["*"]
        }
      ]
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudLabels:
    kubernetes.io/cluster/ops.k8s.nearform.net: owned
  cloudProvider: aws
  configBase: s3://agrium-k8-kops-state-store/ops.k8s.nearform.net
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-eu-central-1a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-eu-central-1a
      name: a
    name: events
  externalDns:
    watchIngress: true
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
    featureGates:
      ExpandInUsePersistentVolumes: "true"
  kubeProxy:
      metricsBindAddress: 0.0.0.0
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.14.6
  masterInternalName: api.internal.ops.k8s.nearform.net
  masterPublicName: api.ops.k8s.nearform.net
  networkCIDR: 172.20.0.0/16
  networkID: vpc-071762f65d1a29b67
  networking:
    weave:
      mtu: 8912
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  sshKeyName: kops-ssh-key
  subnets:
  - cidr: 172.20.100.0/22
    name: agrium-k8s-eu-central-1a
    type: Private
    zone: eu-central-1a
    id: subnet-034fed59df314183f
  - cidr: 172.20.104.0/22
    name: agrium-k8s-eu-central-1b
    type: Private
    zone: eu-central-1b
    id: subnet-083c8ba72edd1a47c
  - cidr: 172.20.108.0/22
    name: agrium-k8s-eu-central-1c
    type: Private
    zone: eu-central-1c
    id: subnet-022155a520213b59a
  - cidr: 172.20.0.0/22
    name: utility-eu-central-1a
    type: Utility
    zone: eu-central-1a
    id: subnet-0b1d1c3b54e61f16b
  - cidr: 172.20.4.0/22
    name: utility-eu-central-1b
    type: Utility
    zone: eu-central-1b
    id: subnet-0b0719cfc422965ae
  - cidr: 172.20.8.0/22
    name: utility-eu-central-1c
    type: Utility
    zone: eu-central-1c
    id: subnet-0ecb2b4ae845e4c7b
  topology:
    bastion:
      bastionPublicName: bastion.ops.k8s.nearform.net
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  
  labels:
    kops.k8s.io/cluster: ops.k8s.nearform.net
  name: bastions
spec:
  image: kope.io/k8s-1.14-debian-stretch-amd64-hvm-ebs-2019-08-16
  machineType: t2.micro
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: bastions
  role: Bastion
  subnets:
  - utility-eu-central-1a
  - utility-eu-central-1b
  - utility-eu-central-1c

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  
  labels:
    kops.k8s.io/cluster: ops.k8s.nearform.net
  name: master-eu-central-1a
spec:
  image: kope.io/k8s-1.14-debian-stretch-amd64-hvm-ebs-2019-08-16
  machineType: m3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-central-1a
  role: Master
  subnets:
  - agrium-k8s-eu-central-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  
  labels:
    kops.k8s.io/cluster: ops.k8s.nearform.net
  name: nodes
spec:
  cloudLabels:
    kubernetes.io/cluster/ops.k8s.nearform.net: owned
  image: kope.io/k8s-1.14-debian-stretch-amd64-hvm-ebs-2019-08-16
  machineType: m4.large
  maxSize: 3
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - agrium-k8s-eu-central-1a
  - agrium-k8s-eu-central-1b
  - agrium-k8s-eu-central-1c

