apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: versionechoer
  name: versionechoer
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: versionechoer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: versionechoer
    spec:
      automountServiceAccountToken: false
      containers:
      - image: pmcgrath/versionechoer:1.0
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /liveness
            port: 5000
        name: echoer
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /readiness
            port: 5000
      securityContext:
        runAsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: versionechoer
  name: versionechoer
spec:
  ports:
  - name: http
    port: 80
    targetPort: 5000
  selector:
    app.kubernetes.io/name: versionechoer
