defaults: &defaults
  docker:
    - image: mariusv/devops-toolbox:0.1
  environment:
    DOCKER_REPO: "REPO URI"
    DOCKER_WORKLOAD: "workload docker name"
    AWS_ECR_REGION: "eu-central-1"
    AWS_EKS_REGION: "eu-central-1"
    CLUSTER_NAME: "ops.k8s.nearform.net"
version: 2
jobs:
  gateway:
    <<: *defaults
    steps:
      run:
        name: "Holding for input"
        command: "echo 1"
  install:
    <<: *defaults
    working_directory: ~/
    steps:
      - checkout
      - run:
          name: "Create TF state storage"
          command: |
            if [ $(aws s3 ls | grep ops.k8s.nearform.net-tf-state | wc -l) -eq 0 ]; then
            aws s3api create-bucket --bucket ${TF_STATE_STORE_BUCKET} --region ${AWS_DEFAULT_REGION} --create-bucket-configuration LocationConstraint=${AWS_DEFAULT_REGION}
            aws s3api put-bucket-versioning --bucket ${TF_STATE_STORE_BUCKET} --versioning-configuration Status=Enabled
            fi
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy-terraform:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "terraform init"
          command: "cd terraform && terraform init"
      - run:
          name: "Terraform apply"
          command: "cd terraform && terraform apply -auto-approve"
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy-kops:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Do something"
          command: "ls -l"
      - persist_to_workspace:
          root: .
          paths:
            - .
  test-cluster:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Do something"
          command: "ls -l"
      - persist_to_workspace:
          root: .
          paths:
            - .
  bootstrap:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Install Helm"
          command: "ls -l"
      - run:
          name: "Do magic"
          command: "ls -l"
      - persist_to_workspace:
          root: .
          paths:
            - .
  decomission-kops:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Install Helm"
          command: "ls -l"
      - run:
          name: "Do magic"
          command: "ls -l"
      - persist_to_workspace:
          root: .
          paths:
            - .
  decomission-terraform:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Install Helm"
          command: "ls -l"
      - run:
          name: "Do magic"
          command: "ls -l"
      - persist_to_workspace:
          root: .
          paths:
            - .
  cleanup:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Install Helm"
          command: "ls -l"
      - run:
          name: "Do magic"
          command: "ls -l"
      - persist_to_workspace:
          root: .
          paths:
            - .

workflows:
  version: 2
   infrastructure-destroy:
     jobs:
      - gateway:
          type: approval
      - install:
          requires:
            - gateway
      - decomission-kops:
          requires:
            - install
      - decomission-terraform:
          requires:
            - decomission-kops
      - cleanup:
          requires:
            - decomission-terraform
  infrastructure-deploy:
    jobs:
      - gateway:
          type: approval
      - install:
          requires:
            - gateway
      - deploy-terraform:
          requires:
            - install
      - deploy-kops:
          requires:
            - deploy-terraform
      - test-cluster:
          requires:
            - install
            - deploy-terraform
            - deploy-kops
      - bootstrap:
          requires:
            - test-cluster
