defaults: &defaults
  docker:
    - image: mariusv/devops-toolbox:0.1
  working_directory: ~/
  environment:
    ALLOW_TERMINATION: 1
version: 2
jobs:
  gateway:
    <<: *defaults
    steps:
      - run:
          name: "Holding for input"
          command: "echo 1"
  install:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: "Create TF state storage"
          command: |
            if [ $(aws s3 ls | grep ops.k8s.nearform.net-tf-state | wc -l) -eq 0 ]; then
            aws s3api create-bucket --bucket ${TF_STATE_STORE_BUCKET} --region ${AWS_DEFAULT_REGION} --create-bucket-configuration LocationConstraint=${AWS_DEFAULT_REGION}
            aws s3api put-bucket-versioning --bucket ${TF_STATE_STORE_BUCKET} --versioning-configuration Status=Enabled
            fi
      - run:
          name: "terraform init"
          command: "cd terraform && terraform init -backend-config=\"bucket=${TF_STATE_STORE_BUCKET}\" -backend-config=\"region=${AWS_DEFAULT_REGION}\""
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy-terraform:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Terraform apply"
          command: "cd terraform && terraform apply -input=false -auto-approve"
      - run:
          name: "Extract terraform outputs"
          command: |
            mkdir -p data/{values,snippets}
            cd terraform
            terraform output nets > ../data/snippets/nets.yaml
            terraform output kops-values > ../data/values/values.yaml
            terraform output private-key > ~/data/ssh-key
            terraform output kops-id > ../data/kops-username
            terraform output kops-secret) > ../data/kops-password
            terraform output build-toolbox-ecr > ../data/ecr.yaml
      - store_artifacts:
          path: "~/data/ssh-key"
      - store_artifacts:
          path: "~/data/ecr.yaml"
      - store_artifacts:
          path: "~/data/kops-username"
      - store_artifacts:
          path: "~/data/kops-password"
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy-kops:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Creating kops template"
          command: "kops toolbox template --template kops/cluster-template.yaml --values data/values/values.yaml --snippets data/snippets --format-yaml > cluster.yaml"
      - run:
          name: "Applying kops template"
          command: "cat cluster.yaml"
      - persist_to_workspace:
          root: .
          paths:
            - .
  test-cluster:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Do something"
          command: "ls -l"
      - persist_to_workspace:
          root: .
          paths:
            - .
  bootstrap:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Install Helm"
          command: "ls -l"
      - run:
          name: "Do magic"
          command: "ls -l"
      - persist_to_workspace:
          root: .
          paths:
            - .
  decomission-kops:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Destroy Kops"
          command: "ls -l"
      - persist_to_workspace:
          root: .
          paths:
            - .
  decomission-terraform:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "terraform destroy"
          command: "cd terraform && terraform destroy -iput=false -auto-approve"
      - persist_to_workspace:
          root: .
          paths:
            - .
  cleanup:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Install Helm"
          command: "ls -l"
      - run:
          name: "Do magic"
          command: "ls -l"
      - persist_to_workspace:
          root: .
          paths:
            - .

workflows:
  version: 2
  infrastructure-destroy:
    jobs:
      - gateway:
          type: approval
      - install:
          requires:
            - gateway
      - decomission-kops:
          requires:
            - install
      - decomission-terraform:
          requires:
            - decomission-kops
      - cleanup:
          requires:
            - decomission-terraform
  infrastructure-deploy:
    jobs:
      - gateway:
          type: approval
      - install:
          requires:
            - gateway
      - deploy-terraform:
          requires:
            - install
      - deploy-kops:
          requires:
            - deploy-terraform
      - test-cluster:
          requires:
            - install
            - deploy-terraform
            - deploy-kops
      - bootstrap:
          requires:
            - test-cluster
