apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
{{ include "versionechoer.labels" . | indent 4 }}
  name: {{ include "versionechoer.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: {{ include "versionechoer.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: {{ include "versionechoer.name" . }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 5000
        livenessProbe:
          httpGet:
            path: /liveness
            port: http
        readinessProbe:
          httpGet:
            path: /readiness
            port: http
        resources:
          {{- toYaml .Values.resources | trim | nindent 10 }}
      securityContext:
        {{- toYaml .Values.securityContext | trim | nindent 8 }}
