apiVersion: v1
kind: Service
metadata:
  labels:
{{ include "versionechoer.labels" . | indent 4 }}
  name: {{ include "versionechoer.fullname" . }}
spec:
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: http
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "versionechoer.name" . }}
  type: {{ .Values.service.type }}
